---
title: "Newport_SSINP"
output: html_document
date: '2022-08-03'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadLibraries, echo=FALSE, message=FALSE}
library(tidyverse)

```

```{r fileLocations, echo=FALSE}
# Directory path on Luke's machine
setwd("~/Documents/Oyster/Rcode")
NewportDir = '../data/Newport_SSINP/'
WestcliffEelgrassDir = 'Westcliff/Eelgrass/'

# Collated calibration data from May 2019, used for Nov 2019 + 2020 oyster deployments
gapecalibfile = '../data/calibration/201905_calibrations.csv'
combogapefile='../data/combogape/'

#meta file with serial numbers
metafile='../data/Newport_SSINP/field_metadata_withedits_2022-2023.csv'
```


```{r gapeFunctions, echo=showcode}

# A set of functions originally taken from MussleTracker_data_proc4.R to 
# handle the gape data


###############################################################################	
# A function to determine where there are gaps of missing data, so that we can 
# apply a filter to the good chunks of data. Most filters fail if there are NAs
# present, and our remaining gaps in the data are big enough that they probably
# shouldn't be smoothed-over anyhow. 
#' A function to find the start and end indices of numeric data in a vector. 
#' Useful for dealing with timeseries that have gaps, and operations that need
#' to operate the separate chunks of contiguous numeric values
#' @param value A vector of numeric values, with NAs 
#' @return A data frame with 2 columns, Start and End, which contain the row
#' indices for the first good and last good values in each contiguous run of
#' numeric values. 	
gapBounds <- function (values){
	# This function returns a data frame of 2 columns, start + end, that give
	# the row indices of the start and end of each run of good data in the 
	# input vector. It should handle data streams that start with NAs and
	# should handle streams that end with NAs. 
	
	# Use run length encoding function to find NA gaps
	gaps = rle(is.na(values))
	# If the first entry in gaps is TRUE, this indicates that the data started
	# with NA values.
	if (gaps$values[1] == TRUE) {
		startNA = TRUE	# Data started with NAs
	} else {	
		startNA = FALSE	 # Data started with real values
	}
	# If the last entry in gaps is TRUE, the data end on NAs
	if (gaps$values[length(gaps$values)] == TRUE){
		endNA = TRUE	# Data ends with NAs
	} else {
		endNA = FALSE	# Data ends with real values
	}
	
	# The number of gaps with value == TRUE is the number of good runs of data
	# and gaps with value == FALSE are the starts of runs of NAs. This will
	# get the number of FALSE (negated to TRUE) values in gaps. A dataset
	# ending in good data will have a last entry in gaps of FALSE. 
	numgaps = sum(!gaps$values)
	
	# Create the output data frame
	results = data.frame(Start = integer(numgaps), End = integer(numgaps))
	
	if (!startNA) {
		# If startNA == FALSE (started on good data, the first entry should 
		# always be 1 (1st row) 
		# If there are no gaps, the
		# contents of gaps$lengths will just be the length of the values vector
		results$Start[1] = 1
		results$End[1] = gaps$lengths[1]
	} else if (startNA){
		# However, if the dataset starts with NAs, the first entry in gaps will
		# be the index of the first good data, while the 2nd entry will be the 
		# start of the next stretch of NAs
		results$Start[1] = gaps$lengths[1]+1
		results$End[1] = sum(gaps$lengths[1:2])
	}
	
	# If there is more than 1 entry in gaps$lengths, process the other gaps
	j = 2; # counter
	if (numgaps > 1){
		if (!startNA & endNA){
			# If the dataset ends on NAs (TRUE last), truncate gapind by 1
			gapind = seq(2,length(gaps$lengths)-1, by = 2)
		} else if (!startNA & !endNA) {
			# If the dataset ends on good values (FALSE last)
			gapind = seq(2,length(gaps$lengths), by = 2)
		} else if (startNA & endNA) {
			# If dataset starts on NAs (TRUE 1st) and ends on NAs (TRUE last)
			gapind = seq(3, length(gaps$lengths)-1, by = 2)
		} else if (startNA & !endNA) {
			# If dataset starts on NAs (TRUE 1st) and ends on good data 
			# (FALSE last)
			gapind = seq(3, length(gaps$lengths), by = 2)
		}	
		# Step through the rest of the gaps object to find the start and end
		# points of each stretch of good data. 
		for (i in gapind){
			nextstart = sum(gaps$lengths[1:i]) + 1
			nextend = sum(gaps$lengths[1:(i+1)])
			results$Start[j] = nextstart
			results$End[j] = nextend
			j = j + 1
		}
	} # end of if (numgaps > 1)
	results	# return the results dataframe, 2 columns Start and End
}

################################################################################
### hallFilter function
#' A function to apply a Butterworth 1st order low-pass filter to a vector
#'  of data. If there are NA values in the original data, they will be 
#'  preserved in the output vector. The filter is set to filter at 1/10 the
#' original sampling rate (which is 5 sec interval (0.2Hz), producing an approximate
#' 50-second window of smoothing. Raw input data are initially centered on 0
#' to avoid artifacts at the start of the filter, and the output is re-centered
#' at the original starting value after the filtering is applied. 
#' 
#' @param hallData A vector of hall effect data.
#' @return A vector of filtered hall effect sensor data.
#'  
hallFilter = function(hallData){	
	# Define a butterworth low-pass filter, 1st order, to filter at 1/10 the 
	# sampling rate (which was 5 secs (0.2Hz))
	#myfilter = signal:::butter(1,0.1,type='low', plane = 'z')
	# Find the start and end of any gaps in the data set using the gapBounds
	# function defined earlier
	mygaps = gapBounds(hallData)
	# Apply the filter to the good runs of data
	for (i in 1:nrow(mygaps)){
		# Extract the run of good data
		dats = hallData[mygaps$Start[i]:mygaps$End[i]]
		# Find the offset of the data from zero
		offset = dats[1]
		# Subtract the offset off of all of the data in this run
		# (The butterworth filter returns large transient values at the start
		# of the run if the value is much different from zero)
		dats = dats - offset
		# Call the filter routine to apply the filter
		yfiltered = signal:::filter(myfilter,dats)
		# Add the offset back on so the data are back on their original scale
		yfiltered = yfiltered + offset
		# Write the filtered data back into the data vector
		hallData[mygaps$Start[i]:mygaps$End[i]] = yfiltered
	}
	# Round the filtered data back to the nearest whole number, since these
	# represent ADC count data.
	hallData = round(hallData)
	hallData	# return vector of filtered data
}

################################################################################
# Define a non-linear function that allows you to plug in a Hall effect sensor
# count value and generate an approximate distance in mm. Supply the 
# coefficients a, b, c, based on a nls curve fit for counts as a function of
# distance. 
# In the above equation, 'a' is the effective asymptotic value
# 'b' is the range of values between the minimum observed count and the 
# asymptotic count (so a min count of 400 and asymptote of 500 gives b = 100)
# 'c' is effectively a curvature parameter. Larger values of 'c' yield a 
# smaller change in Distance as Counts increases (when back-calculating 
# Distance), particularly for low Counts values. 
#' A function to back-calculate an asymptotic function to generate a distance
#' value based on a hall effect sensor count value input.
#' 
#' @param Counts A vector of hall effect sensor values, usually between 0 and 
#' 512 (from a 10-bit analog-to-digital converter). 
#' @param a A parameter derived from an asymptotic curve fit, representing the
#' asymptotic count value
#' @param b A parameter derived from an asymptotic curve fit, representing the 
#' range from the minimum count up to the asymptotic value. 
#' @param c A parameter derived from an asymptotic curve fit, representing the
#' curvature of the fit. 
#' @returns A vector of distance values of the same length as Counts. Any input 
#' values equal or larger than the asymptotic parameter a will return Inf.

DistFromCounts <- function(Counts, a,b,c){
	dist = (log((Counts - a)/(-1*b))) / (-1*c)
	dist
}


################################################################################
### percentileRange function
# Define a function to calculate the average reading for the upper and lower
# x percentile of the hall effect data. 
#' Calculate the average of the specified lower percentile and upper percentile
#' and return the values that correspond to those means (rounded to integers).
#' 
#' @param hallData A vector of analog-to-digital convertor counts from a 
#' Hall effect sensor. The values are assumed to start low (<512) when the 
#' magnetic signal is strong (close to sensor) and increase towards 512 when
#' the magnetic signal is weak (far from sensor).
#' @param percentileLim A set of 2 numeric values between 0 and 1, usually close
#'  to 0.01 and 0.99
#' used to define the lower and upper percentile limits. A value of 
#' 0.01 would cause the 1st percentile sensor values to be used as the
#' lower limits, and similar for the upper limit. 
#' @return A two element vector for the lower and upper values in hallData that
#' represent the lower and upper percentiles

percentileRange <- function (Hallvec, percentileLim = c(0.01,0.99)){
	# Remove any NA's
	temp = Hallvec[!is.na(Hallvec)]
	# Reorder the values smallest to largest
	temp = temp[order(temp)]
	# Get the index of the entry closest to percentileLim
	indx = round(percentileLim[1] * length(temp)) 
	# Calculate the mean value for the lower % of closed valve values and
	# round up to the next integer value
	closedVal = ceiling(mean(temp[1:indx]))
	
	# Now do the same for the other end of the range of hall effect values
	# These would normally represent "fully open" readings near 512 if the 
	# magnet and sensor are situated so that the magnet drives the signal
	# below 512 when it approaches the sensor as the shell valves close. 
	indx = round(percentileLim[2] * length(temp))
	# Calculate the mean value for the upper % of open valve values and round
	# down to the next integer value
	openVal = floor(mean(temp[indx:length(temp)]))
	result = c(closedVal, openVal)
	result # return the two values, always smallest then largest
}

################################################################################
### calcPercentGapeNLME function
# Use this function to calculate the percentage gape (0-100%)
# This calculates the baseline fully-closed and fully-open values based
# on the upper and lower 1% of hall effect sensor data for the given range
# of rows in the input dataset. 
# Supply a vector of Hall effect sensor data. This function will find any 
# gaps in the vector (NA's) and calculate a new baseline for each section of
# good data. 
#' Convert hall effect count data (integer values from analog-digital converter)
#' into percent gape values between 0 and 100\%. 
#' 
#' @param hallData A vector of analog-to-digital convertor counts from a 
#' Hall effect sensor. The values are assumed to start low (<512) when the 
#' magnetic signal is strong (close to sensor) and increase towards 512 when
#' the magnetic signal is weak (far from sensor).
#' @param cRegress A linear model object (lm) for the relationship of 'c' versus
#' the log-transform of 'b'. 
#' @param percentileLim A numeric value between 0 and 1, usually close to 0.01,
#' used to define the lower and upper percentile limits (the upper limit is 
#' mirrored from the lower limit). A value of 
#' 0.01 would cause the 1st and 99th percentile sensor values to be used as the
#' lower and upper limits.
#' @return A vector of the same length as hallData containing percentage values 
#' 0 to 100, representing the shell valve gape 
#' opening. A value of 0 is a fully closed shell (strong magnetic signal) and
#' 100 is a fully open shell (weak magnetic signal).

calcPercentGapeNLME <- function (hallData, cRegress, percentileLim = 0.01){
	require(nlme)
	# Get the row indices for the major gaps that exist now
	mygaps = gapBounds(hallData)
	# Create an empty output vector of the same length as the input data. 
	outputData = vector(mode = 'numeric', length = length(hallData))
	outputData[] = NA # Convert all the values to NA to begin with
	
	# Now for each section of the input data, calculate the percent gape. This
	# involves using the entries in mygaps to subset the input data and 
	# calculate individual percentile values for each contiguous section of
	# data. If there is a significant gap in the data (usually > 30 sec), the
	# percentages will be re-calculated for each contiguous section of data. 
	# This should accommodate any sensor/magnet re-glueing issues. 
	for (i in 1:nrow(mygaps)){
		st = mygaps$Start[i]
		end = mygaps$End[i]
		# First calculate the upper and lower 1% values of the Hall readings
		# These will be count values representing the fully closed (lowest) 
		# and fully open (highest, closest to 512) values.
		myrange = percentileRange(hallData[st:end], 
				percentileLim = percentileLim)
		
		# Now truncate count values that are outside myrange to the limits of myrange.
		rowIndices = which(hallData[st:end] < myrange[1])
		hallData[(st+rowIndices)] = myrange[1]
		rowIndices = which(hallData[st:end] > myrange[2])
		hallData[(st+rowIndices)] = myrange[2]
		
		# The count values are now constrained within a range that should 
		# encompass fully closed (0mm) to fully open (~5mm gape). Now calculate
		# the approximate gape opening based on the count values and a curve
		# fit. 
		
		# Define the three asymptotic curve parameters a,b,c using the data for
		# the current chunk of data.
		aVal = max(hallData[st:end],na.rm=TRUE)+1 # add 1 count to avoid Inf output
		bVal = max(hallData[st:end],na.rm=TRUE) - 
				min(hallData[st:end],na.rm=TRUE)
		# Calculating c requires the linear model object supplied as cRegress,
		# which will use the log-transformed 'b' value to estimate the 'c'
		# parameter
		cVal = predict(cRegress, newdata = list(b = bVal))
		
		# Use DistFromCounts function to estimate valve gape distance using the 
		# input hall effect count data at each time point and the 
		# parameters a,b,c
		temp2 = DistFromCounts( hallData[st:end], 
				a = aVal,
				b = bVal,
				c = cVal)
		
		# Replace any fully-open Inf values with the largest good max distance
		temp2[is.infinite(temp2)] = max(temp2[is.finite(temp2)])
		# Replace any negative distance values with the 0 distance value
		temp2[which(temp2 < 0)] = 0
		# Convert to percentage by dividing all distances by the maximum value
		outputData[st:end] = (temp2 / max(temp2,na.rm=TRUE)) * 100
		
		# Round the values off to a reasonable precision
		outputData[st:end] = round(outputData[st:end],1)
		
	}	
	outputData	# return the output data vector
}	# end of calcPercentGapeNLME function

#cRegressEstimate helps calibrate sensors using CalibFileName.csv file 
################################################################################
################################################################################
# Function cRegressEstimate
# Currently this represents the best data showing how the relationship between
# magnet signal and distance is repeatable and consistent among different
# magnets (all from the same batch/part number). As such, a non-linear curve
# can be fit to the various calibration runs to generate a set of 
# coefficients a,b,c for an asymptotic curve. Then the values from a field 
# mussel can be analyzed to determine the asymptotic maximum count value
# (widest opening) and minimum count value (fully closed), which give us the
# parameters for coefficients a and b in the curve fit. Because the curvature
# coefficient 'c' of the curves is very linear with respect to the coefficient
# 'b' (range of readings), we can plug in the max vs. min range for a particular
# mussel and use that to predict the appropriate curve coefficient 'c' to use
# for that mussel. 

#' A function to generate a set of hall effect calibration data and estimate
#' the relationship between parameters 'b' and 'c', for later use in the 
#' function calcPercentGapeNLME(). 
#' @param SN A text string naming the board serial number, in the form 'SN21'
#' @param Channel numeric value naming the Hall effect sensor channel to be 
#' calibrated (expected values 0-15). 
#' @param gapeCalibFile A text path to the file that holds Hall effect
#' calibration data
#' @return cRegress A linear model object representing the best fit regression
#'  of parameter 'c' on the log-transformed parameter 'b'. 

cRegressEstimate <- function(SN, Channel, gapeCalibFile){
	require(nlme)
	# Create an identifier for the board/channel combination 'SN21Ch01'
	if (Channel < 10){
		newChannel = paste0('0',as.character(Channel))
	} else {
		newChannel = as.character(Channel)
	}
	currentID = paste0(SN,'Ch',newChannel)
	 
	# Get list of calibration data
	gapeCalibs = read.csv(gapeCalibFile)

	gapeCalibs$Serial = factor(gapeCalibs$Serial)
	gapeCalibs$Trial = factor(gapeCalibs$Trial)
	# Create a unique identifier for each board/channel combination,
	# ensuring that the Channel number is always 2 digits
	gapeCalibs$ID = factor(paste0(gapeCalibs$Serial,'Ch',
					ifelse(gapeCalibs$HallChannel<10,
							paste0('0',gapeCalibs$HallChannel),
							gapeCalibs$HallChannel)))

# For any instance where magnet was set up so that values climbed above 512
# when close to the sensor, reverse those values so they are all less than 
# 512. 
	for (i in 1:length(levels(gapeCalibs$ID))){
		if (max(gapeCalibs$Reading[gapeCalibs$ID == 
								levels(gapeCalibs$ID)[i]]) > 515){
			gapeCalibs$Reading[gapeCalibs$ID == 
							levels(gapeCalibs$ID)[i]] = 1023 - 
					gapeCalibs$Reading[gapeCalibs$ID == 
									levels(gapeCalibs$ID)[i]]
		}
	}	
	# Begin generating the asymptotic curve fit parameters for the magnetic
# hall effect sensor data. 
	gC2 = groupedData(Reading~Distance.mm|ID/Trial,data=gapeCalibs)
	

# Fit the asymptotic model and generate a set of coefficient values
# This will adjust each set of a,b,c coefs based on a random effect of
# magID and Trial. 
	
	# Fit separate curves to each group (trial) in the grouped data frame
	mod3 = nlsList(Reading~a-(b*exp(-c*Distance.mm)), 
			data = subset(gC2,subset = ID == currentID), 
			start = c(a = 460, b = 60, c = 0.3),
			control = list(minFactor = 1e-9, msMaxIter = 200, maxiter = 200))
# Extract the a,b,c coefficients and put them in a data frame
	abcvals = data.frame(a = coef(mod3)[,1], b = coef(mod3)[,2],
			c = coef(mod3)[,3])
	
# The fit between 'b' and 'c' can be linearized with a log transform of 'b'
	cRegress = lm(c~log(b), data = abcvals)  

#	plot(c~`log(b)`, data = cRegress$model) # Plot the original data
#	abline(cRegress) # fitted regression line
	
	# Return cRegress as the output
	cRegress
}  # end of cRegressEstimate function.
################################################################################

```

```{r importFunctions, echo=showcode}
#' Concatenate multiple daily gape files into one data frame
#' 
#' @param filenames A vector of filenames (including path) to be concatenated. The
#' input files should contain a column named DateTime that will be converted to 
#' a POSIXct timestamp class. 
#' @param myTimeZone Specify the time zone of the timestamp data in the imported
#' DateTime column. Default = UTC
#' @param verbose A logical argument specifying whether to show verbose progress
#' output during file ingestion
#' @return A data frame consisting of the input files concatenated and sorted 
#' chronologically. 

ConcatGapeFiles <- function(filenames, myTimeZone = 'UTC',verbose=FALSE){
	if(verbose){
		pb = txtProgressBar(min=0,max = length(filenames), style = 3)
	}
# Open the raw data files and concatenate them.
	for (f in 1:length(filenames)){
		if(verbose) setTxtProgressBar(pb,f)
		
		dattemp = read.csv(filenames[f])
		###########################
		# Columns:
		# POSIXt: elapsed seconds since 1970-01-01 00:00:00 (unix epoch) in whatever
		#         timezone the sensor was set to during deployment. Presumably UTC
		# DateTime: human-readable character date and time, in whatever timezone the
		#         sensor was set to during deployment 
		# Hallx: Raw analog to digital converter value for the indicated Hall effect 
		#		channel. There are 16 channels (numbered 0-15) on the GapeTracker
		# Battery.V:  Supply battery voltage
		#########################
		# Convert the DateTime column to a POSIXct object.
		dattemp$DateTime = as.POSIXct(dattemp$DateTime, tz=myTimeZone) 	
		
		
		# Concatenate the data files. 
		if (f == 1){
			dat = dattemp
		} else if (f > 1){
			dat = rbind(dat,dattemp)
		}
	}
	if(verbose) close(pb)
# Reorder the concatenated data frame by the DateTime values in case the files
# were not fed in in chronological order
	dat = dat[order(dat$DateTime),]
}

########################################
#' Load a csv data file containing deployment metadata
#' 
#' The deployment metadata file should contain entries for each oyster and 
#' its associated hall effect sensor channel for a given period of time denoted 
#' by the timestamps in 2 columns titled StartIncludeUTC and EndIncludeUTC, which
#' are assumed to have Excel-formatted date and time stamps in the UTC time zone
#' marking the start and end of each known-good deployment period (thus ignoring
#' time periods when the sensors were pulled from the mooring for maintenance or
#' other interruptions). 
#' 
#' @param filename The path and filename of the metadata csv file
#' @param timezone The timezone of the timestamp data in the metadata file. 
#' Default = UTC.
#' @return A data frame containing the same original columns as the metadata 
#' file, but with timestamps formatted as POSIXct values in the appropriate
#' time zone. 

loadFieldMetaData <- function(filename, timezone = 'UTC'){
	metadata = read.csv(file= filename)
	metadata$StartIncludeUTC = as.POSIXct(metadata$StartIncludeUTC,
			format = '%m/%d/%Y %H:%M',tz = 'UTC')
	metadata$EndIncludeUTC = as.POSIXct(metadata$EndIncludeUTC,
			format = '%m/%d/%Y %H:%M',tz = 'UTC')
	metadata # return data frame
}


##############################################################
#' Excise questionable rows of data from Hall effect sensor data
#' 
#' @param halldata A dataframe containing timestamps and hall effect data from
#' multiple sensors.
#' @param metadf A data frame of start and end times to use in the data set,
#' formatted as POSIXct time stamps in the same time zone as values in the 
#' timestamps argument. The data frame should also have a column with an OysterID
#' and a hall effect sensor channel for that oyster for each time period laid
#' out in the data frame.
#' @param maxGapFill The maximum number of missing values in the input time 
#' series to impute via linear interpolation. Gaps longer than this will remain 
#' as NA values. 
#' 
#' @return A data frame with columns
#' added on for each oyster with available hall effect sensor data. Missing 
#' periods of hall effect values will be denoted with NA values.  


exciseHall = function(halldata, metadf, maxGapFill = 12) {
	# Get the list of unique OysterID values from excisedf
	oysters = unique(metadf$OysterID)
	oysters = oysters[order(oysters)] # reorder if needed 
	
	# Generate output data frame based on initial deployment time and final 
	# raw data time
	time1 = min(metadf$StartIncludeUTC)
	time2 = max(halldata$DateTimeUTC)
	totaltimeseries = seq(time1,time2,by=5) 
	
	for (i in 1:length(oysters)){
		# Create vector to hold hall effect data for this oyster
		temphall = vector(mode='logical',length = length(totaltimeseries))
		temphall[] = NA # Set all entries to NA initially
		# Convert outputdf to a zoo object for easier time handling
		tempoutput = zoo(temphall,order.by = totaltimeseries)
		
		
		# Get the rows in metadf that refer to the current oyster
		oysterRows = metadf[metadf$OysterID == oysters[i],]
		
		for (j in 1:nrow(oysterRows)){
			# Get the hall effect sensor channel for this entry
			tempChannel = as.character(oysterRows$Channel[j])
			# Get the start and end time stamps for this entry
			startTime = oysterRows$StartIncludeUTC[j]
			endTime = oysterRows$EndIncludeUTC[j]
			# Extract the relevant set of data from halldata
			temp = halldata[halldata$DateTimeUTC>=startTime & 
							halldata$DateTimeUTC<=endTime, 
					c('DateTimeUTC',tempChannel)]
			# Convert to a zoo timeseries object
			temp = zoo(temp[,2],order.by=temp[,1],frequency = 1)
			# Insert the temp hall data into the zoo object tempoutput
			# The syntax is fun here: On the left side of the equals sign,
			# you want a set of indices in tempoutput where the time value
			# from tempoutput is found %in% the time values of temp. And on the
			# right side of the equals sign, you want to get hall effect values
			# from temp where the time value in temp is found %in% the time
			# values of tempoutput (a much bigger set)
			tempoutput[index(tempoutput) %in% index(temp)] = 
					temp[index(temp) %in% index(tempoutput)]
		}
		
 		#For brief gaps in the data, use the zoo package function 
		# na.approx() to generate linearly-interpolated values for the missing
		# data. For 5-second interval data, a maxGapFill = 12 will fill up to
		# a 1 minute gap max.
		# If the dataset starts off or ends with NAs, they will not be altered
		tempoutput = na.approx(tempoutput, maxgap = maxGapFill, na.rm=FALSE)
		
		# Convert tempoutput back to a data frame and stick it onto an output
		# dataframe
		if (i == 1){
			outputdf = data.frame(DateTimeUTC = index(tempoutput), tempoutput)
			names(outputdf)[2] = as.character(oysters[i])
		} else if (i > 1) {
			tempoutput = as.data.frame(tempoutput)
			outputdf = cbind(outputdf,tempoutput)
			names(outputdf)[ncol(outputdf)] = as.character(oysters[i])
		}
	}
	outputdf  # return outputdf	
	
} # End of exciseHall function


```

```{r concatGapeFunction}
# This function deals with the GAPE data files that have an unnecessary comma at the end of each row of data, which messes with the read.csv import function

#' Concatenate multiple daily gape files into one data frame
#' 
#' @param filenames A vector of filenames (including path) to be concatenated
#' @param myTimeZone A text representation of the timezone that the datalogger
#' clock was set to (i.e. 'UTC' or 'PST8PDT' or 'etc/GMT+8')
#' @param verbose Turn on the progress bar if set to TRUE
#' @return A data frame consisting of the input files concatenated and sorted 
#' chronologically. 

ConcatGapeFiles <- function(filenames, myTimeZone = 'UTC',verbose=TRUE){
	if(verbose){
		pb = txtProgressBar(min=0,max = length(filenames), style = 3)
	}
# Open the raw data files and concatenate them.
	for (f in 1:length(filenames)){
		if(verbose) setTxtProgressBar(pb,f)
		con = file(filenames[f])
		line1 = scan(con, what='character', nlines = 1, sep = ',', quiet = TRUE)
		line2 = scan(con, what = 'character', skip = 1, nlines = 1, sep = ',', quiet = TRUE)
		close(con)
		if (length(line2) > length(line1)){
		  # There is an extra column in the data section due to a trailing comma
		  # in the data rows
		  # so we need to handle the column names correctly on import
		  dattemp = read.csv(filenames[f], skip = 1, header = FALSE,
		                    col.names = c(line1,'Extra'))
		  # Remove the extra column at the end
		  dattemp = dattemp[,-(ncol(dattemp))]
		} else {
		  # number of headers is same as number of data columns, so just import 
		  # as normal
		  dattemp = read.csv(filenames[f])
		}
		
		
		###########################
	# Columns:
	# POSIXt: elapsed seconds since 1970-01-01 00:00:00 (unix epoch) in whatever
	#         timezone the sensor was set to during deployment. Presumably UTC
	# DateTime: human-readable character date and time, in whatever timezone the
	#         sensor was set to during deployment 
	# SN: serial number of the sensor
	# Hall: raw Hall effect gape sensor reading
	# TempC: temperature in Celsius from TMP107 sensor on the heart rate dongle	
	# Battery.V:  Supply battery voltage
		#########################
	# Convert the DateTime column to a POSIXct object.
		dattemp$DateTime = as.POSIXct(dattemp$DateTime, tz=myTimeZone) 	

		
		# Concatenate the data files. 
		if (f == 1){
			dat = dattemp
		} else if (f > 1){
			dat = rbind(dat,dattemp)
		}
	}
	if(verbose) close(pb)
# Reorder the concatenated data frame by the DateTime values in case the files
# were not fed in in chronological order
	dat = dat[order(dat$DateTime),]
}

```

```{r, echo=FALSE}
# Get a list of the IR heart sensor files by looking for filenames that end in IR.csv
IRfilenames = dir(path = paste0(NewportDir, WestcliffEelgrassDir, 'SN107_2022-07-13_2022-07-30'), full.names=TRUE, pattern= "*IR.csv")

# Get a list of gape (and temperature) filenames by looking for filenames that end in GAPE.csv
gapefiles = dir(path = paste0(NewportDir, WestcliffEelgrassDir, 'SN107'), full.names=TRUE, pattern= "*GAPE.csv")
# These files tend to have a comma after the last column's data, which makes read.csv think there's one more column of data than there are names in the header row, which then treats the 1st column of POSIXt values as row numbers, which is unfortunate. You need to handle that appropriately. 

#for loop that says go through SN107 and find all files, combine them together, and spit out combogapefile at end
#import csv metadata_with edits.use unique() on first column. Save result as "serialnumber"
metafile = loadFieldMetaData(filename = 
         '../data/Newport_SSINP/field_metadata_withedits_2022-2023.csv')
serialnumber=unique(metafile[,1])
######################################## 
for(i in (serialnumber)){
  
  gapecombo=dir(path='../data/Newport_SSINP', full.names = TRUE, pattern=i)
}

gapecombo=paste0(ConcatGapeFiles('../data', myTimeZone="UTC",verbose=FALSE),serialnumber[i],"combogape.csv")

gapecombo=dir(path='../data/Newport_SSINP/De Anza/Eelgrass', full.names = TRUE, pattern='SN107')
#use "serialnumber" (every row is serial number to be processed) of all serial numbers in field. in this directory, look for folder "SN107" then get list of all gape files in that folder and process them. with dir function can find folder names using something like pattern= "SN107". 
#make for loop go through vector. 
#at end get calculated ranges for sensors. 
#paste0(gapeDir(###place where it saves),serialnumber[i],"combogape.csv")
#if there's no folder for serial number (haven't downloaded data yet) then have it end the loop and go back to the start and try the next number
```

#combine data from different files/days into continuous time series
```{r loadLPL,echo=showcode, eval = evalAll}
# Generate the list of LPL field data file names
#LPLfiles = dir(path = gapeRawDir, full.names=TRUE, pattern = '*.csv')  
 
# Use the ConcatGapeFiles function to ingest the raw data files
gapedat = ConcatGapeFiles(gapefiles, myTimeZone = 'UTC', verbose = FALSE)
# Rename the DateTime column to indicate that these values were set in the UTC time zone 
names(gapedat)[2] = 'DateTimeUTC'
# Create an additional column with timestamps in the local standard time zone
# Pacific Standard Time (this will still ignore daylight savings time)
gapedat$DateTimePST = gapedat$DateTimeUTC
attr(gapedat$DateTimePST,'tzone') = 'etc/GMT+8'

# Call the loadFieldMetaData function to import the metadata file
#LPLmeta2019 = loadFieldMetaData(filename = 
			#	'../data/LPL_field_metadata_2019-2020.csv')  

```

#Can use if have meta data file
#cut out specific times from meta data that shouldn't be used
```{r processRawHallData,echo=showcode, eval = evalAll}
# Call exciseHall function to generate a master data frame of raw hall effect readings from the oysters that were present in the field. This will remove the other sensor channels in the raw data files that didn't have oysters  attached. This function could take several minutes to run for bigger data sets
#gapemaster = exciseHall(halldata = gapedat, metadf = LPLmeta2019)      

# Generate a set of oyster locations (bottom or surface) from the metadata file
#LPLoysterLocations = unique(LPLmeta2019[,c(2,4)])
#LPLoysterLocations = LPLoysterLocations[order(LPLoysterLocations$Location),]

# Create an additional column with timestamps in the local standard time zone
# Pacific Standard Time (this will still ignore daylight savings time)
#LPLmaster$DateTimePST = LPLmaster$DateTimeUTC 
#attr(LPLmaster$DateTimePST,'tzone') = 'etc/GMT+8'
```

```{r concatGape}
# Use the concatenate function defined above to put together all of the gape files stored in Gapefilenames 
SN107_gape = ConcatGapeFiles(Gapefilenames, myTimeZone = 'UTC', verbose = TRUE)

```

```{r testPlot}
# Plot the timeseries of gape values
plot(SN107_gape$DateTime, SN107_gape$Hall, type = 'l')

#subset only time in field before death
SN107_gape_fieldonly <- SN107_gape %>%
                        filter(DateTime >= as.POSIXct('2022-07-15 13:00:00',tz="UTC") & DateTime<= as.POSIXct('2022-07-20 07:42:00',tz="UTC"))

plot(SN107_gape_fieldonly$DateTime, SN107_gape_fieldonly$Hall, type = 'l')

```

```{r calcPercentageGape,echo=showcode, eval = evalAll}
# The sensors for the LPL oysters were originally calibrated on board SN21,
# so use value that to extract relevant calibration data from the calibration
# file stored in calibFileName
gapeSN = 'SN21'  
  
gape.perc = gapedat
  

#converts Hall column to 0-100 values so now on scale of 1-100
	#currentChannel = colnames(gapedat)[i]
	# Locate the channel number from currentChannel name
	#chNumRegex = regexpr('[0-9]+', currentChannel)
	# Extract the channel number
	#chNum = as.numeric(substr(currentChannel,
				#	start=chNumRegex,
				#	stop=(chNumRegex+attr(chNumRegex,'match.length')-1)))
	# Generate the regression fit for the relationship between curvature parameter
	# 'c' and the log-transform of 'b'.
  chNum=1
	cRegress = cRegressEstimate(gapeSN, chNum,gapecalibfile)
	# Convert the Hall effect values into estimated percent gape (0-100%)
	gape.perc[,"hallpercent"] = calcPercentGapeNLME(gapedat[,4], cRegress, 
			percentileLim = c(0.01,0.95))
	 
# The output data frame LPLgape.pc should now contain estimated percentage
# gape values for each oyster at each time point. 

# Save a copy of the data frame that can be reopened for quicker execution
# of this script instead of re-running the whole raw data processing
write.csv(gape.perc,
		file = paste0(gapeDir,SN107combogapefile),
		row.names=FALSE)

# Create a decimated copy of the data frame (1 sample per minute) to make it
# easier to handle
LPLgape.perc.dec = LPLgape.perc[seq(1,nrow(LPLgape.perc), by = 12),]
write.csv(LPLgape.perc.dec,
		file = paste0(gapeDir,LPL1minGapeFile),
		row.names=FALSE)

```

